# Generated by Django 4.2.5 on 2023-09-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseList',
            fields=[
                ('Case_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Case_Number', models.IntegerField(unique=True)),
                ('Short_Case_Name', models.CharField(max_length=100)),
                ('Petitioner', models.CharField(max_length=100)),
                ('Respondent', models.CharField(max_length=100)),
                ('Court_of_origin', models.CharField(max_length=100)),
                ('Case_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('aadhar_number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
