# Generated by Django 4.2.5 on 2023-09-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselist',
            name='user_id',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
