# Generated by Django 4.1.5 on 2023-09-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_caselist_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caselist',
            name='Case_Number',
        ),
        migrations.AddField(
            model_name='caselist',
            name='Case_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caselist',
            name='matter',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
