# Generated by Django 4.2.5 on 2023-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_caselist_case_number_caselist_case_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselist',
            name='critical_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
